apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-egressgateway
  namespace: istio-system
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - qa-t-test.apps.cluster-fiserv-71cc.fiserv-71cc.example.opentlc.com
    - dev-t-test.apps.cluster-fiserv-71cc.fiserv-71cc.example.opentlc.com
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-tls
  namespace: istio-system
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: tls-outside-mesh
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
      portLevelSettings:
      - port:
          number: 443
        tls:
          mode: ISTIO_MUTUAL
          sni: dev-t-test.apps.cluster-fiserv-71cc.fiserv-71cc.example.opentlc.com
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway
  namespace: istio-system
spec:
  host: dev-t-test.apps.cluster-fiserv-71cc.fiserv-71cc.example.opentlc.com
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    portLevelSettings:
    - port:
        number: 443
      tls:
        mode: MUTUAL
        credentialName: test-certs
        sni: t-test.apps.cluster-fiserv-71cc.fiserv-71cc.example.opentlc.com
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: DestinationRule
# metadata:
#   name: egressgateway-for-tls-qa
#   namespace: istio-system
# spec:
#   host: istio-egressgateway.istio-system.svc.cluster.local
#   subsets:
#   - name: tls-outside-mesh-qa
#     trafficPolicy:
#       loadBalancer:
#         simple: ROUND_ROBIN
#       portLevelSettings:
#       - port:
#           number: 443
#         tls:
#           mode: ISTIO_MUTUAL
#           sni: qa-t-test.apps.cluster-fiserv-71cc.fiserv-71cc.example.opentlc.com
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: DestinationRule
# metadata:
#   name: egressgateway-qa
#   namespace: istio-system
# spec:
#   host: qa-t-test.apps.cluster-fiserv-71cc.fiserv-71cc.example.opentlc.com
#   trafficPolicy:
#     loadBalancer:
#       simple: ROUND_ROBIN
#     portLevelSettings:
#     - port:
#         number: 443
#       tls:
#         mode: MUTUAL
#         clientCertificate: /etc/istio/test-certs/tls.crt
#         privateKey: /etc/istio/test-certs/tls.key
#         caCertificates: /etc/istio/test-ca/ca.crt
#         sni: t-test.apps.cluster-fiserv-71cc.fiserv-71cc.example.opentlc.com
