apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway1
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
     number: 443
     name: https-443
     protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - nodejs-fs-mesh-qa.apps.cluster-6bdf.6bdf.example.opentlc.com
--- 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-routing-config
  namespace: istio-system
spec:
  hosts:
  - nodejs-fs-mesh-qa.apps.cluster-6bdf.6bdf.example.opentlc.com
  gateways:
  - gateway1
  http:
  - route:
    - destination:
        host: http-mtls-git.fs-mesh-qa.svc.cluster.local
--- 
# apiVersion: networking.istio.io/v1alpha3
# kind: DestinationRule
# metadata:
#   name: nodejs
# spec:
#   host: nodejs.fs-mesh-qa.svc.cluster.local