apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/deewhyweb/http-mtls.git
  labels:
    app: http-mtls-git
    app.kubernetes.io/component: http-mtls-git
    app.kubernetes.io/instance: http-mtls-git
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: http-mtls-git-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "12"
  name: http-mtls-git
  namespace: fs-mesh-qa
  resourceVersion: "45296"
  selfLink: /api/v1/namespaces/fs-mesh-qa/services/http-mtls-git
spec:
  clusterIP: 172.30.135.160
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8443
  selector:
    app: http-mtls-git
    deploymentconfig: http-mtls-git
  sessionAffinity: None
  type: ClusterIP
